import assert from 'node:assert/strict'
import {mkdir,writeFile} from 'node:fs/promises'
import {resolve} from 'node:path'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const origin=process.env.LIFE_URL || 'http://127.0.0.1:4178'
const output=resolve(process.env.LIFE_EVIDENCE || 'test-output/payments')
await mkdir(output,{recursive:true})
const browser=await chromium.launch({headless:true,channel:process.env.LIFE_BROWSER_CHANNEL || 'chrome'})
const page=await browser.newPage({viewport:{width:1440,height:1000}})
const errors=[],checks=[]
page.on('pageerror',e=>errors.push(e.message))
async function screenshot(name){await page.screenshot({path:resolve(output,name+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow')}
try {
 await page.goto(origin)
 await page.getByRole('button',{name:'查看毕业季草坪音乐会',exact:true}).waitFor()
 await screenshot('catalog-desktop')
 await page.getByRole('button',{name:'登录 / 注册',exact:true}).click()
 await page.getByRole('button',{name:'还没有账号？创建账号'}).click()
 await page.locator('[name=username]').fill('pay_'+Date.now())
 await page.locator('[name=displayName]').fill('支付验收')
 await page.locator('[name=password]').fill('Local-ui-payment-'+Date.now())
 await page.getByRole('button',{name:'注册并登录',exact:true}).click()
 await page.getByRole('button',{name:'退出登录',exact:true}).waitFor()
 await page.getByRole('button',{name:'查看毕业季草坪音乐会',exact:true}).click()
 await page.getByRole('button',{name:'立即抢票',exact:true}).first().click()
 await page.getByRole('button',{name:'模拟支付',exact:true}).first().waitFor({timeout:20000})
 await page.getByRole('button',{name:'模拟支付',exact:true}).first().click()
 await page.getByRole('button',{name:'确认模拟支付',exact:true}).waitFor()
 await screenshot('checkout-desktop')
 await page.setViewportSize({width:390,height:844})
 await screenshot('checkout-mobile')
 let first=true,channelIds=[]
 await page.route('**/sandbox-receipt',async route=>{
   channelIds.push(route.request().postDataJSON().channelId)
   if(first){first=false;await route.fetch();await route.abort('failed')}
   else await route.continue()
 })
 await page.getByRole('button',{name:'确认模拟支付',exact:true}).click()
 await page.getByText('支付成功',{exact:true}).waitFor({timeout:12000})
 checks.push('lost callback response recovered by status polling')
 assert.equal(channelIds.length,1)
 await screenshot('paid-mobile')
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.reload()
 await page.getByRole('button',{name:'我的票夹',exact:false}).click()
 await page.locator('.order .status.confirmed').first().waitFor()
 checks.push('paid order survives reload')
 await page.getByRole('button',{name:'查看历史查询',exact:true}).click()
 await page.getByRole('heading',{name:'历史订单',exact:true}).waitFor()
 assert(!(await page.locator('body').innerText()).includes('32 张'))
 await screenshot('orders-mobile')
 checks.push('history wording and mobile layout')
 await page.getByRole('button',{name:'活动广场',exact:true}).click()
 await page.getByRole('button',{name:'查看毕业季草坪音乐会',exact:true}).click()
 await page.getByRole('button',{name:'立即抢票',exact:true}).nth(1).click()
 await page.getByRole('button',{name:'模拟支付',exact:true}).waitFor({timeout:20000})
 await page.getByRole('button',{name:'模拟支付',exact:true}).click()
 await page.getByRole('button',{name:'确认模拟支付',exact:true}).waitFor()
 const session=await (await page.request.get(origin+'/v2/auth/me')).json()
 const requests=await (await page.request.get(origin+'/v2/account/requests')).json()
 const pending=requests.items.find(x=>x.orderState==='PENDING_CONFIRM')
 assert(pending)
 const cancelled=await page.request.post(origin+'/v2/requests/'+pending.id+'/cancel',{headers:{'X-CSRF-Token':session.csrfToken,'X-Account-ID':session.user.id}})
 assert(cancelled.ok())
 await page.getByRole('button',{name:'确认模拟支付',exact:true}).click()
 await page.getByText('已退款',{exact:true}).waitFor({timeout:15000})
 await screenshot('late-payment-refunded-mobile')
 checks.push('late receipt after order cancellation is refunded')
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.locator('.order').filter({has:page.locator('.status.cancelled')}).getByRole('button',{name:'付款记录'}).click()
 await page.getByText('已退款',{exact:true}).waitFor()
 checks.push('refund status can be reopened from a closed order')
 assert.deepEqual(errors,[])
 await writeFile(resolve(output,'results.json'),JSON.stringify({checks,errors,passed:true},null,2))
 console.log(JSON.stringify({checks,passed:true}))
} finally {await browser.close()}
